<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Version information for local_aiquizgenerator.
 *
 * @package    qbank_llmjudge
 * @copyright  2026 Renat Furs <fursrenat@gmail.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['aigenerationerror'] = 'An error occurred while processing a request. Please try again.';
$string['analyze'] = 'Analyze';
$string['apply'] = 'Apply';
$string['clarity'] = 'Clarity';
$string['cognitive_level'] = 'Cognitive level';
$string['cognitivedifficulty'] = 'Intended cognitive difficulty';
$string['conciseness'] = 'Conciseness';
$string['correctness'] = 'Correctness';
$string['create'] = 'Create';
$string['details'] = 'Full Feedback';
$string['discrimination'] = 'Discrimination';
$string['evaluate'] = 'Evaluate';
$string['evaluatequestions'] = 'Evaluate the questions with AI';
$string['evaluationcompleted'] = 'Evaluation was completed successfully.';
$string['evaluations'] = 'LLM Evaluations';
$string['feedback'] = 'Feedback';
$string['invalidjson'] = 'The JSON generated by AI is invalid. Please try again.';
$string['llmscore'] = 'LLM Score';
$string['maxscore'] = 'Max overall score';
$string['missingquestionsselected'] = 'Missing selected questions';
$string['model'] = 'Model';
$string['noevaluationsfound'] = 'No evaluation was found';
$string['overallscore'] = 'Score';
$string['pluginname'] = 'LLM Judge';
$string['questionscountexceeded'] = 'Maximum number of questions to be evaluated is 10';
$string['reliability'] = 'Reliability';
$string['remember'] = 'Remember';
$string['score'] = 'Scores per Criterion';
$string['suggestions'] = 'Suggestions';
$string['timecreated'] = 'Last evaluation date';
$string['understand'] = 'Understand';
$string['viewdetails'] = 'View evaluation details';
